### PR TITLE
Added new widget.

### PR DESCRIPTION
**Pull request by peterkacinec**
- dashboard for Club Manager now shows new widget of transfer requests from Club.

[Review on Reviewable](https://reviewable.io/reviews/membery/engine/26)

### CODE REVIEW

**Comment by sosik** [comment]
chyba preklad do tretieho jazyka a jeden preklad je urcite nie ok

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/client/js/x-translation.js, line 1074 [r1]](https://reviewable.io:443/reviews/membery/engine/26#-JvxngCpJcSriMYOCa-k)** ([raw file](https://github.com/membery/engine/blob/036619de256eb5a0d97e08b92c4091b2e3167375/src/client/js/x-translation.js#L1074)):</sup>
????
- chyba preklad do tretieho jazyka

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/26)

**Comment by peterkacinec** [comment]
prepac, moja nepozornost. uz som opravil commit a pushol

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/26)

**Comment by sosik** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/26)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
