### PR TITLE
Upload progress

### PR DESCRIPTION
**Pull request by lukas-cap**
[Review on Reviewable](https://reviewable.io/reviews/membery/engine/20)

### CODE REVIEW

**Comment by sosik** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/js/xpsui/directives/uploadable-file.js, line 36 [r1]](https://reviewable.io:443/reviews/membery/engine/20#-JvTy4aH3Ib5R3myOFmn)** ([raw file](https://github.com/membery/engine/blob/d5b73f6ac5967fba1e452af49cdecaa608ae54aa/src/client/js/xpsui/directives/uploadable-file.js#L36)):</sup>
empty line after function declaration :-1: 

---

<sup>**[src/client/js/xpsui/directives/uploadable-image.js, line 18 [r1]](https://reviewable.io:443/reviews/membery/engine/20#-JvU0WlhO3X5R6g42InV)** ([raw file](https://github.com/membery/engine/blob/d5b73f6ac5967fba1e452af49cdecaa608ae54aa/src/client/js/xpsui/directives/uploadable-image.js#L18)):</sup>
what is "hidden" attribute? shouldn't it be done by css?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/20)

**Comment by lukas-cap** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/client/js/xpsui/directives/uploadable-image.js, line 18 [r1]](https://reviewable.io:443/reviews/membery/engine/20#-JvU0WlhO3X5R6g42InV)** ([raw file](https://github.com/membery/engine/blob/d5b73f6ac5967fba1e452af49cdecaa608ae54aa/src/client/js/xpsui/directives/uploadable-image.js#L18)):</sup>
It's a HTML5 attribute to hide an element. I didn't know if there is an advantage to doing it in css. This was easier to work with because I can just call removeAttr and Attr to show or hide the element.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/20)

**Comment by lukas-cap** [comment]
updated

**Comment by sosik** [comment]
Please check what your changes done on portal. there are upload image components too a dn file upload components.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/20)

**Comment by sosik** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/20)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
