### PR TITLE
Added sender address variables to config.js

### PR DESCRIPTION
**Pull request by lukas-cap**
- added sender addresses for processsing errors and new requests

[Review on Reviewable](https://reviewable.io/reviews/membery/engine/15)

### CODE REVIEW

**Comment by sosik** [comment]
u should put note into compatibility.md event without version raise as I it is necessary to update local configuration when deploying on servers. Please update request

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/15)

**Comment by sosik** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/15)

**Comment by sosik** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/server/config.js, line 28 [r1]](https://reviewable.io:443/reviews/membery/engine/15#-JvU4g3ZjIwwHYYRc8bB)** ([raw file](https://github.com/membery/engine/blob/f84ba7afc9e46a77bd6b2e29b23223d094e1b31c/src/server/config.js#L28)):</sup>
Please change all addresses to websupport

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/15)

**Comment by lukas-cap** [comment]
updated

**Comment by sosik** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/15)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
