### PR TITLE
[FIXED #99890102] Fixed form validations

### PR DESCRIPTION
**Pull request by lukas-cap**
- validation marks now show up where they should
- xpsui-date-edit is now validated properly

[Review on Reviewable](https://reviewable.io/reviews/membery/engine/19)

### CODE REVIEW

**Comment by sosik** [comment]
All this stuff needs deeper revision, it looks generally broken.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/js/xpsui/directives/validity-mark.js, line 80 [r1]](https://reviewable.io:443/reviews/membery/engine/19#-JvTwDdwYCaxlBRutlTG)** ([raw file](https://github.com/membery/engine/blob/791f45c72b97e01172aa21954eea083057f82d94/src/client/js/xpsui/directives/validity-mark.js#L80)):</sup>
space at bigginig of line :-1: 

---

<sup>**[src/client/js/xpsui/directives/validity-mark.js, line 84 [r1]](https://reviewable.io:443/reviews/membery/engine/19#-JvTwS_0jekdYpB1rwtH)** ([raw file](https://github.com/membery/engine/blob/791f45c72b97e01172aa21954eea083057f82d94/src/client/js/xpsui/directives/validity-mark.js#L84)):</sup>
this stuff is probably completely wrong. newVal will be true only in case of boolean may be it should be without comparison simply (newVal) to check that variable is set.

---

<sup>**[src/client/js/xpsui/directives/validity-mark.js, line 87 [r1]](https://reviewable.io:443/reviews/membery/engine/19#-JvTx8lMdsVItz3Q0vc1)** ([raw file](https://github.com/membery/engine/blob/791f45c72b97e01172aa21954eea083057f82d94/src/client/js/xpsui/directives/validity-mark.js#L87)):</sup>
Cannot understand why validation mark sets value of field, it should just react for validation state not reset values. wrong behaviour

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/19)

**Comment by lukas-cap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/js/xpsui/directives/validity-mark.js, line 84 [r1]](https://reviewable.io:443/reviews/membery/engine/19#-JvTwS_0jekdYpB1rwtH)** ([raw file](https://github.com/membery/engine/blob/791f45c72b97e01172aa21954eea083057f82d94/src/client/js/xpsui/directives/validity-mark.js#L84)):</sup>
newVal in this case is new value of the variable submitPrepare, which is boolean (is it ?) .

---

<sup>**[src/client/js/xpsui/directives/validity-mark.js, line 87 [r1]](https://reviewable.io:443/reviews/membery/engine/19#-JvTx8lMdsVItz3Q0vc1)** ([raw file](https://github.com/membery/engine/blob/791f45c72b97e01172aa21954eea083057f82d94/src/client/js/xpsui/directives/validity-mark.js#L87)):</sup>
have no clue, this just changed {} in the model to null.  Everything seemed to work fine without it. I left it in there because I didn't know why we wanted to do that. I'll look into it more.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/19)

**Comment by sosik** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/client/js/xpsui/directives/objRequired.js, line 8 [r2]](https://reviewable.io:443/reviews/membery/engine/19#-JvmoXOTek9-mcHHoX_G)** ([raw file](https://github.com/membery/engine/blob/a6ccd742c226c0138c1c47a7144df32ed4f0519e/src/client/js/xpsui/directives/objRequired.js#L8)):</sup>
it may be, that when attributes on html element are defined in order <div xpsui-obj-required required> that native angular implementation of required overrides obj-required field. Please confirm.
There is one property of directive, that can define order in which are directives evaluated, please investigate and test.

---

<sup>**[src/client/js/xpsui/services/form-generator.js, line 41 [r2]](https://reviewable.io:443/reviews/membery/engine/19#-JvmpK37NW5NT1HA8L39)** ([raw file](https://github.com/membery/engine/blob/a6ccd742c226c0138c1c47a7144df32ed4f0519e/src/client/js/xpsui/services/form-generator.js#L41)):</sup>
check specifically for objectlink please

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/19)

**Comment by sosik** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/19)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
