### PR TITLE
Fix match generator.

### PR DESCRIPTION
**Pull request by peterkacinec**
- generator now automatically fills season, ageCategory, matchNumber and homeClub, awayClub.
- refereeReport now include homeClub and awayClub fields for setting security "Zapisovatel".

[Review on Reviewable](https://reviewable.io/reviews/membery/engine/36)

### CODE REVIEW

**Comment by sosik** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/js/xpsui/services/generators-generator.js, line 90 [r1]](https://reviewable.io:443/reviews/membery/engine/36#-JwanPpB3V9wV_ghzo2J)** ([raw file](https://github.com/membery/engine/blob/db1b9484a651863f2bf099b1848d1c4d45fb1971/src/client/js/xpsui/services/generators-generator.js#L90)):</sup>
Peto, nastav si eslint ako linter zdrojoveho kodu, ide to vo vsetkych editoroch ktore pouzivame. Tiez si pridaj kazdy subor ktory editujes s kodom do grunt/config/eslint na spravne miest, bude to kontrolovat formatovanie. rob to pre kazdy subor ktoreho sa dotknes.

---

<sup>**[src/client/js/xpsui/services/generators-generator.js, line 138 [r1]](https://reviewable.io:443/reviews/membery/engine/36#-JwankZvPETjTECvOLCm)** ([raw file](https://github.com/membery/engine/blob/db1b9484a651863f2bf099b1848d1c4d45fb1971/src/client/js/xpsui/services/generators-generator.js#L138)):</sup>
v sucasnosti uz objectlink neouziva pole registry, ale schema, skontroluj si to

---

<sup>**[src/client/js/xpsui/services/generators-generator.js, line 216 [r1]](https://reviewable.io:443/reviews/membery/engine/36#-JwanxEAuBzn5BBlt4xj)** ([raw file](https://github.com/membery/engine/blob/db1b9484a651863f2bf099b1848d1c4d45fb1971/src/client/js/xpsui/services/generators-generator.js#L216)):</sup>
je tento callback na spravnom mieste? podla mna nie a ma byt v tom promise all. takto sa ti zavola este skor ako updatnes tie tabulky a iba nahodou to nepadne. skontroluj si to

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/36)

**Comment by peterkacinec** [comment]
<sup>**[src/client/js/xpsui/services/generators-generator.js, line 90 [r1]](https://reviewable.io:443/reviews/membery/engine/36#-JwanPpB3V9wV_ghzo2J)** ([raw file](https://github.com/membery/engine/blob/db1b9484a651863f2bf099b1848d1c4d45fb1971/src/client/js/xpsui/services/generators-generator.js#L90)):</sup>
ok, to som zvladol, mam nainstalovane rozsirenie priamo v Sublime Text 3. Vyriesil som vsetky errory az na: Expected indentation of 3 characters but found 2.
to som googlil a nevedel som si dat rady.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/36)

**Comment by peterkacinec** [comment]
<sup>**[src/client/js/xpsui/services/generators-generator.js, line 216 [r1]](https://reviewable.io:443/reviews/membery/engine/36#-JwanxEAuBzn5BBlt4xj)** ([raw file](https://github.com/membery/engine/blob/db1b9484a651863f2bf099b1848d1c4d45fb1971/src/client/js/xpsui/services/generators-generator.js#L216)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/36)

**Comment by peterkacinec** [comment]
<sup>**[src/client/js/xpsui/services/generators-generator.js, line 138 [r1]](https://reviewable.io:443/reviews/membery/engine/36#-JwankZvPETjTECvOLCm)** ([raw file](https://github.com/membery/engine/blob/db1b9484a651863f2bf099b1848d1c4d45fb1971/src/client/js/xpsui/services/generators-generator.js#L138)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/36)

**Comment by sosik** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/36)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
