### PR TITLE
[FINISHED #99117936] rememberMe functionality

### PR DESCRIPTION
**Pull request by tomatell**
- implemented rememberMe functionality
- cleaned the updated codes

[Review on Reviewable](https://reviewable.io/reviews/membery/engine/1)

### CODE REVIEW

**Comment by sosik** [comment]
Reviewed 7 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/js/xpsui/controller/security-login-ctrl.js, line 12 [r2]](https://reviewable.io:443/reviews/membery/engine/1#-JvTog5neX74IFa1u9ep)** ([raw file](https://github.com/membery/engine/blob/7afa41fb186733fbe2c8a758348cbc1f3b69ee1c/src/client/js/xpsui/controller/security-login-ctrl.js#L12)):</sup>
Cookie is not required on client this way, it is not used in this file at all

---

<sup>**[src/server/securityController.js, line 1246 [r1]](https://reviewable.io:443/reviews/membery/engine/1#-Juup683_kvaUHI9FxIO)** ([raw file](https://github.com/membery/engine/blob/e62196ace09be103ed83f65f9f99776bd52b044a/src/server/securityController.js#L1246)):</sup>
https://en.wikipedia.org/wiki/HTTP_cookie#Expires_and_Max-Age

Expirity 0 means sessio cookie, this is not what you want

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/1)

**Comment by tomatell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/client/js/xpsui/controller/security-login-ctrl.js, line 12 [r2]](https://reviewable.io:443/reviews/membery/engine/1#-JvTog5neX74IFa1u9ep)** ([raw file](https://github.com/membery/engine/blob/7afa41fb186733fbe2c8a758348cbc1f3b69ee1c/src/client/js/xpsui/controller/security-login-ctrl.js#L12)):</sup>
$cookies is not used in the security login control anymore. Therefore, it will be removed and have the commit amended.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/1)

**Comment by sosik** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/engine/1)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
